# Questao 1

In [ ]:
import numpy as np
from sklearn import preprocessing
from sklearn.datasets import load_iris


iris_dataset = load_iris()
dados_originais = iris_dataset['data']
uma_feature = dados_originais[:, [0]]

print(iris_dataset.data[0])
print(f"Uma feature: {uma_feature[0:5]}")
print(f"Dados originais: {dados_originais[0:5]}")

normalizador = preprocessing.StandardScaler()
dados_transformados = normalizador.fit_transform(uma_feature)
print(f"Dados normalizados: {dados_transformados[0:5]}\n\n")


print(f"média: {np.mean(dados_transformados)}")
print(f"desvio padrao: {np.std(dados_transformados)}")


[5.1 3.5 1.4 0.2]
Uma feature: [[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]]
Dados originais: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Dados normalizados: [[-0.90068117]
 [-1.14301691]
 [-1.38535265]
 [-1.50652052]
 [-1.02184904]]


média: -4.736951571734001e-16
desvio padrao: 1.0


# Questao 2


In [3]:

import numpy as np
from sklearn import preprocessing
from sklearn.datasets import load_iris


iris_dataset = load_iris()
dados_originais = iris_dataset['data']
uma_feature = dados_originais[:, [0]]

desvio_padrao = np.std(uma_feature)
media = np.mean(uma_feature)  

padronizados=[]
for exemplo in uma_feature:
    amostra=exemplo[0]    
    menos_media=amostra - media  
    std=menos_media / desvio_padrao
    padronizados.append(std)

print(padronizados[0:5])


[np.float64(-0.9006811702978088), np.float64(-1.1430169111851105), np.float64(-1.3853526520724133), np.float64(-1.5065205225160652), np.float64(-1.0218490407414595)]


# Questão 3:
Realize a regularização das features do Iris Dataset utilizando a norma Euclidiana (L2). Exiba os resultados obtidos.

In [14]:
from sklearn.preprocessing import Normalizer
from sklearn import datasets
import numpy as np


iris = datasets.load_iris()
features = iris.data 


normalizer_l2 = Normalizer(norm="l2") 
features_normalized_l2 = normalizer_l2.transform(features)


print("Features Originais (primeiras 5 observações):\n", features[:5])
print("\nFeatures Normalizadas (L2, primeiras 5 observações):\n", features_normalized_l2[:5])


first_observation_norm = np.linalg.norm(features_normalized_l2)
print("\nNorma L2 da primeira observação normalizada:", first_observation_norm)

Features Originais (primeiras 5 observações):
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Features Normalizadas (L2, primeiras 5 observações):
 [[0.80377277 0.55160877 0.22064351 0.0315205 ]
 [0.82813287 0.50702013 0.23660939 0.03380134]
 [0.80533308 0.54831188 0.2227517  0.03426949]
 [0.80003025 0.53915082 0.26087943 0.03478392]
 [0.790965   0.5694948  0.2214702  0.0316386 ]]

Norma L2 da primeira observação normalizada: 12.247448713915889


# Questao 5   

In [10]:
from sklearn.datasets import load_breast_cancer
from sklearn.feature_selection import SelectPercentile
from sklearn.model_selection import train_test_split
import numpy as np



rng = np.random.RandomState(42)

cancer = load_breast_cancer()
noise = rng.normal(size=(len(cancer.data), 50))
X_w_ruido = np.hstack([cancer.data, noise])

X_train, X_test, y_train, y_test = train_test_split(
    X_w_ruido, cancer.target, random_state=0, test_size=.5)


metade_features = SelectPercentile(percentile=50)
metade_features.fit(X_train, y_train)

X_train_features_filtradas = metade_features.transform(X_train)

print("X_train.shape: {}".format(X_train.shape))
print("X_train_features_filtradas.shape: {}".format(X_train_features_filtradas.shape))

X_train.shape: (284, 80)
X_train_features_filtradas.shape: (284, 40)
