# exercício 1

In [ ]:
import numpy as np
from sklearn import preprocessing
from sklearn.datasets import load_iris


iris_dataset = load_iris()
dados_originais = iris_dataset['data']
uma_feature = dados_originais[:, [0]]

print(iris_dataset.data[0])
print(f"Uma feature: {uma_feature[0:5]}")
print(f"Dados originais: {dados_originais[0:5]}")

normalizador = preprocessing.StandardScaler()
dados_transformados = normalizador.fit_transform(uma_feature)
print(f"Dados normalizados: {dados_transformados[0:5]}\n\n")


print(f"média: {np.mean(dados_transformados)}")
print(f"desvio padrao: {np.std(dados_transformados)}")


[5.1 3.5 1.4 0.2]
Uma feature: [[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]]
Dados originais: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Dados normalizados: [[-0.90068117]
 [-1.14301691]
 [-1.38535265]
 [-1.50652052]
 [-1.02184904]]


média: -4.736951571734001e-16
desvio padrao: 1.0
